### ISSUE TITLE
Use as low .NET version requirement as possible

### ISSUE THREAD

**Issue by carlhoerberg** [stevenlovegrove/MqttDotNet#10]
Many projects are still on 2.0 or 3.5, and can't use the project currently as it requires 4.5..

**Comment by ChrisMcKee** [comment]
To be fair 4.5 has been out since 2012. 3.5 is from 2007.  Probably time to look at bringing your project up-to-date :)

**Comment by carlhoerberg** [comment]
2 years is not a long time in the corporate .NET world. .NET libraries should seek to use as low version number as possible if they want adoption, while internal projects can use high numbers. Is there specific 4.5 features you're relying on?

**Comment by ChrisMcKee** [comment]
Not the most active of projects. Probably better to grab a fork and try to downgrade it; see what snaps.

**Comment by stevenlovegrove** [comment]
I don't think anything should break if the project is downgraded. If you want to try it, I'll accept a pull request to make it permanent. I've been avoiding merging a Pull Request (https://github.com/stevenlovegrove/MqttDotNet/pull/9) because of it's use of LINQ that I don't know how to rewrite. Anybody that feels like rewriting that fix is 2.0 compatible form is also welcome to...

**Comment by stevenlovegrove** [comment]
https://github.com/stevenlovegrove/MqttDotNet/commit/de29d40ff3c56d8528bb1b56f9281b00a874f657 hopefully solves this issue

**Comment by carlhoerberg** [comment]
Thank you!!
